DROP TABLE IF EXISTS EMPLOYEE_TASK;
DROP TABLE IF EXISTS DOCUMENT;
DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS POSITION;
DROP TABLE IF EXISTS TASK;
DROP TABLE IF EXISTS ADDRESS;

CREATE TABLE TASK(
 ID LONG GENERATED ALWAYS AS IDENTITY,
 NAME VARCHAR(30) NOT NULL,
 DESCRIPTION VARCHAR(60) NOT NULL,
 TYPE VARCHAR(20) NOT NULL,
 PRIORITY VARCHAR(10) NOT NULL,
 DATE_AND_TIME TIMESTAMP NOT NULL,
 STATUS VARCHAR(30) NOT NULL,
 PRIMARY KEY (ID)
);

CREATE TABLE POSITION(
 ID LONG GENERATED ALWAYS AS IDENTITY,
 NAME VARCHAR(30) NOT NULL,
 DESCRIPTION VARCHAR(50) NOT NULL,
 PRIMARY KEY (ID)
);

CREATE TABLE EMPLOYEE(
 ID LONG GENERATED ALWAYS AS IDENTITY,
 USERNAME VARCHAR(255) NOT NULL UNIQUE,
 PASSWORD VARCHAR(255) NOT NULL,
 FIRST_NAME VARCHAR(30) NOT NULL,
 LAST_NAME VARCHAR(30) NOT NULL,
 START_DATE DATE NOT NULL,
 EMAIL VARCHAR(30) NOT NULL UNIQUE,
 POSITION_ID LONG NOT NULL,
 PRIMARY KEY (ID),
 FOREIGN KEY(POSITION_ID) REFERENCES POSITION(ID));

CREATE TABLE DOCUMENT(
 ID LONG GENERATED ALWAYS AS IDENTITY,
 EMPLOYEE_ID LONG NOT NULL,
 DOCUMENT_PATH VARCHAR(255) NOT NULL,
 PRIMARY KEY (ID),
 FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEE(ID)
);

CREATE TABLE EMPLOYEE_TASK(
 ID LONG GENERATED ALWAYS AS IDENTITY,
 EMPLOYEE_ID LONG NOT NULL,
 TASK_ID LONG NOT NULL,
 PRIMARY KEY (ID),
 FOREIGN KEY(TASK_ID) REFERENCES TASK(ID),
 FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEE(ID)
);

INSERT INTO TASK(NAME, DESCRIPTION, TYPE, PRIORITY, DATE_AND_TIME, STATUS) VALUES('Weekly Meeting', 'Discuss project updates', 'Meeting task', 'MEDIUM', '2025-02-27 14:00:00', 'Pending');
INSERT INTO TASK(NAME, DESCRIPTION, TYPE, PRIORITY, DATE_AND_TIME, STATUS) VALUES('Employee Training', 'Conduct Java training', 'Training task', 'CRITICAL', '2025-02-26 09:30:00', 'Pending');
INSERT INTO TASK(NAME, DESCRIPTION, TYPE, PRIORITY, DATE_AND_TIME, STATUS) VALUES('Write Documentation', 'Upload a letter of recommendation from a faculty lecturer', 'Documentation task', 'HIGH', '2025-02-28 10:00:00', 'Pending');
INSERT INTO TASK(NAME, DESCRIPTION, TYPE, PRIORITY, DATE_AND_TIME, STATUS) VALUES('Project Meeting', 'Discuss project goals', 'Meeting task', 'MEDIUM', '2025-03-01 14:00:00', 'Pending');
INSERT INTO TASK(NAME, DESCRIPTION, TYPE, PRIORITY, DATE_AND_TIME, STATUS) VALUES('Technical Training', 'React.js workshop', 'Training task', 'LOW', '2025-02-28 09:00:00', 'Completed');
INSERT INTO TASK(NAME, DESCRIPTION, TYPE, PRIORITY, DATE_AND_TIME, STATUS)
VALUES('Make a cv', 'Write a cv with relevant experience for this position', 'Documentation task', 'HIGH', '2025-02-21 10:00:00', 'Pending');

INSERT INTO POSITION(NAME, DESCRIPTION) VALUES('Software Engineer', 'Develops and maintains software applications');
INSERT INTO POSITION(NAME, DESCRIPTION) VALUES('Project Manager', 'Oversees project progress and delivery');
INSERT INTO POSITION(NAME, DESCRIPTION) VALUES('HR Specialist', 'Manages recruitment and employee relations');

INSERT INTO EMPLOYEE(USERNAME, PASSWORD, FIRST_NAME, LAST_NAME, START_DATE, EMAIL, POSITION_ID) VALUES('user1', 'user1', 'Marko', 'Ivić', '2020-06-01', 'marko.ivic@gmail.com', 1);
INSERT INTO EMPLOYEE(USERNAME, PASSWORD, FIRST_NAME, LAST_NAME, START_DATE, EMAIL, POSITION_ID) VALUES('user2', 'user2', 'Ana', 'Kovač', '2018-04-15', 'ana.kovac@hotmail.com', 2);
INSERT INTO EMPLOYEE(USERNAME, PASSWORD, FIRST_NAME, LAST_NAME, START_DATE, EMAIL, POSITION_ID) VALUES('user3', 'user3', 'Petar', 'Horvat', '2022-01-10', 'petar.horvat@outlook.com', 3);
INSERT INTO EMPLOYEE(USERNAME, PASSWORD, FIRST_NAME, LAST_NAME, START_DATE, EMAIL, POSITION_ID) VALUES('user4', 'user4', 'Ivan', 'Horvat', '2020-01-10', 'ivan.horvat@live.com', 1);
INSERT INTO EMPLOYEE(USERNAME, PASSWORD, FIRST_NAME, LAST_NAME, START_DATE, EMAIL, POSITION_ID) VALUES('anita', 'Anita123', 'Anita', 'Matokovic', '2021-01-11', 'anitamatokovic5@gmail.com', 1);

INSERT INTO DOCUMENT(EMPLOYEE_ID, DOCUMENT_PATH) VALUES(1, 'C:\Users\anita\Downloads\CV_AnitaMatokovic.pdf');
INSERT INTO DOCUMENT(EMPLOYEE_ID, DOCUMENT_PATH) VALUES(2, 'C:\Users\anita\Downloads\AnitaMatokovic.jpg');
INSERT INTO DOCUMENT(EMPLOYEE_ID, DOCUMENT_PATH) VALUES(3, 'C:\Users\anita\Downloads\preporuka_predavaca_Silvio_Plehati.pdf');
INSERT INTO DOCUMENT(EMPLOYEE_ID, DOCUMENT_PATH) VALUES(4, 'C:\Users\anita\Downloads\certificateFromTheFaculty_AnitaMatokovic.pdf');
INSERT INTO DOCUMENT(EMPLOYEE_ID, DOCUMENT_PATH) VALUES(1, 'C:\Users\anita\Downloads\PEF-AnitaMatokovic.pdf');
INSERT INTO DOCUMENT(EMPLOYEE_ID, DOCUMENT_PATH) VALUES(2, 'C:\Users\anita\Downloads\signature_AnitaMatokovic.jpg');
INSERT INTO DOCUMENT(EMPLOYEE_ID, DOCUMENT_PATH) VALUES(3, 'C:\Users\anita\Downloads\eZapis-o-statusu-studenta.pdf');
INSERT INTO DOCUMENT(EMPLOYEE_ID, DOCUMENT_PATH) VALUES(5, 'C:\Users\anita\Downloads\eZapis-o-statusu-studenta.pdf');

INSERT INTO EMPLOYEE_TASK(EMPLOYEE_ID, TASK_ID) VALUES(1, 1);
INSERT INTO EMPLOYEE_TASK(EMPLOYEE_ID, TASK_ID) VALUES(2, 2);
INSERT INTO EMPLOYEE_TASK(EMPLOYEE_ID, TASK_ID) VALUES(3, 3);
INSERT INTO EMPLOYEE_TASK(EMPLOYEE_ID, TASK_ID) VALUES(4, 4);
INSERT INTO EMPLOYEE_TASK(EMPLOYEE_ID, TASK_ID) VALUES(1, 5);
INSERT INTO EMPLOYEE_TASK(EMPLOYEE_ID, TASK_ID) VALUES(2, 6);
INSERT INTO EMPLOYEE_TASK(EMPLOYEE_ID, TASK_ID) VALUES(5, 1);
INSERT INTO EMPLOYEE_TASK(EMPLOYEE_ID, TASK_ID) VALUES(5, 2);
INSERT INTO EMPLOYEE_TASK(EMPLOYEE_ID, TASK_ID) VALUES(5, 3);
INSERT INTO EMPLOYEE_TASK(EMPLOYEE_ID, TASK_ID) VALUES(5, 4);
INSERT INTO EMPLOYEE_TASK(EMPLOYEE_ID, TASK_ID) VALUES(5, 5);
INSERT INTO EMPLOYEE_TASK(EMPLOYEE_ID, TASK_ID) VALUES(5, 6);